apiVersion: goabout.com/v1beta1
# kind: SopsSecretGenerator
kind: ksops
metadata:
    name: n8n-env
annotations:
    argocd.argoproj.io/hook: "PreSync"
    argocd.argoproj.io/hook-delete-policy: "BeforeHookCreation"
    argocd.argoproj.io/job-cleanup: "keep"
    argocd.argoproj.io/sync-wave: "1"
envs:
    - secrets/confidential/n8n.enc.env
